# (Optional) Upload directory (default: $CWD/upload)
upload_dir: /app/upload
# (Optional) Output directory (default: $CWD/output)
output_dir: /app/output
# (Optional) Temporary directory (default: $CWD/tmp)
tmp_dir: /app/tmp
conversion:
  # (Required) Task name
  - name: move-files
    # (Required) Command to run
    cmd:
      - 'mkdir -p {{ output_dir }}\{{ ext }}'
      - 'mv {{ input }} {{ output_dir }}\{{ ext }}\{{ name }}.{{ ext }}'
    extract: (?P<name>.+)\.(?P<ext>.{2,})$
    # (Optional) Upload directory (default: $CWD/upload)
    upload_dir: /app/upload
    # (Optional) Output directory (default: $CWD/output)
    output_dir: /app/output
    # (Optional) Temporary directory (default: $CWD/tmp)
    tmp_dir: /app/tmp
    # (Optional) Include directories (default: false)
    include_dirs: false
    # (Optional) Scan interval (default: 15 seconds)
    scan_interval: 15
    # (Optional) Scan exclude. Allows RegEx. Exclude > Include (default: [])
    scan_exclude:
      # Excludes any jpg or jpeg files
      - .*\.jpe?g
    # (Optional) Scan include. Allows RegEx. Exclude > Include (default: [])
    scan_include:
      # Allows only pdf files
      - .*\.pdf
logs:
  # (Required) Path to logs file (default: $CWD/logs/converter.log)
  path: /app/config/converter.log
  # (Optional) Log level (default: INFO)
  level: 'INFO'